baseURL = "https://blank1729.github.io/blog"
languageCode = "en-us"
title = "An idiot's blog"
theme = "ink-free"
paginate = 5

copyright = "© Copyright notice"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "An idiot's blog"

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "dark"

	# Enable a table of contents
	toc = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Stupid footers :)
	footers = [ 
		"What Tiger King can teach us about x86 Assembly",
		"10 Reasons why gcc SHOULD be re-written in JavaScript - You won't believe #8!"
	]

	# Github base url
	github = "https://github.com/chollinger93/ink-free"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Notes"
url = "/notes"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "Summaries"
url = "/summaries"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/blank1729/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
